version: '3.1'

services:
  code-server:
    image: linuxserver/code-server
    container_name: 'app-code-server'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PASSWORD=terserahlw
      - SUDO_PASSWORD=terserahlw
    volumes:
      - ./docker/vscode:/config
      - ./:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.1.2.3

  postgresql:
    build: ./docker/postgresql
    container_name: 'app-postgresql'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homestead
      PGDATA: /var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.1.2.2

volumes:
  postgres_data:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.1.2.0/24
